# Site settings
title: punchDev Studio
email: sales@punchdev.com
username: punchdev
description: "We are dedicated to building the best web and mobile solutions for your business."
baseurl: ""
url: "http://punchdev.com"

# Build settings
markdown: rdiscount
permalink: pretty
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
