development: &default
  adapter: postgresql
  database: punchdev_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: punchdev_test

production:
  adapter: postgresql
  database: punchdev_production
  pool: 5
  timeout: 5000
